### ISSUE TITLE
RNCCheckbox was not found in the UIManager

### ISSUE THREAD

**Issue by gutwenger** [react-native-checkbox/react-native-checkbox#173]
After running `npm install --save @react-native-community/checkbox` and import `<CheckBox />`, it threw an error as below:-

```
[Unhandled promise rejection: Invariant Violation: requireNativeComponent: "RNCCheckbox" was not found in the UIManager.]
at node_modules/react-native/Libraries/ReactNative/getNativeComponentAttributes.js:28:11 in getNativeComponentAttributes
at node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:116:25 in exports.get
at node_modules/@react-navigation/native/src/useThenable.tsx:26:18 in resolve
```

PS. I'm using expo.

Anyone encountered the same issue? Any solutions? Thanks.

**Comment by ayoub-rouani** [comment]
I faced the same problem now, just restart the project and it works

**Comment by neerajdembla212** [comment]
@ayoub-rouani May I know which version of this library are you using?

**Comment by ayoub-rouani** [comment]
@neerajdembla212   "@react-native-community/checkbox": "^0.5.12",

**Comment by neerajdembla212** [comment]
@ayoub-rouani Can I have a glimpse of your package.json please? the version 0.5.12 is giving same error to me. I guess it is some other package version which is incompatible. 

Following is my package.json

<img width="454" alt="Screenshot 2022-08-02 at 1 43 46 PM" src="https://user-images.githubusercontent.com/13874146/182300528-2784099b-1a49-445e-9e25-cf902dd0ead7.png">

**Comment by ReactNativ** [comment]
` cd ios/ && pod install `

**Comment by kmkz-69** [comment]
If you are using Expo :  [expo install expo-checkbox](https://docs.expo.dev/versions/latest/sdk/checkbox/)

**Comment by HayderEspinoza** [comment]
try installing the pods  `npx pod-install`

**Comment by waqaskhanroghani** [comment]
Rebuild your current app after installing this library.

**Comment by kmkz-69** [comment]
The problem has been solved, please close the problem. @neerajdembla212

**Comment by neerajdembla212** [comment]
@gutwenger Please close the issue. Thanks!

**Comment by dembijeremias** [comment]
this solution didn't work for me. I'm using React Native version 0.63.4
 
![Simulator Screen Shot - Iphone 11 Pro Max - 2023-08-07 at 16 35 43](https://github.com/react-native-checkbox/react-native-checkbox/assets/125599429/f700c102-9871-4b2e-a611-2b0d6bc82722)

**Comment by OumarMaiga** [comment]
> If you are using Expo : [expo install expo-checkbox](https://docs.expo.dev/versions/latest/sdk/checkbox/) it will work

this works for me. Thanks

**Comment by Eddievin** [comment]
Anyone still struggling with this thing. I suffered for 6 hours and this is the solution I got that worked it's magic.
🖱️ Using Expo

Run: 🖱️ expo install expo-checkbox

Then in your project import like this: 🖱️ import CheckBox from "expo-checkbox";

**Comment by tariqmurtuza** [comment]
- cd ios & run **npx pod install**
- Close your application and metro and restart the application by **npx react-native run-ios**

Hopefully it will work.

**Comment by nicholaslee119** [comment]
"AndroidCheckBox"/"RNCCheckbox" not found in UIManager errors were typically caused by the native module not being linked in older setups (manual linking, missing rebuild, or stale Metro cache). With autolinking and the current toolchain (RN 0.82, New Architecture), a clean rebuild resolves this. If you hit this on a recent RN version, please try: (1) reinstall, (2) `cd ios && pod install`, (3) rebuild the native app (not just reload JS), (4) reset Metro cache (`--reset-cache`). Closing as stale — please reopen with your RN version and the steps above tried if it still reproduces.
